name: "install dependencies"

on:
  push:
    branches:
      - master
      - develop

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: "install composer dependencies"
